# name: Push File

# on: push

# jobs:
#   copy-file:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Pushes test file
#       uses: dmnemec/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: './'
#         destination_repo: 'heemankv/lil'
#         # destination_folder: 'test-dir'
#         user_email: 'heemankv@gmail.com'
#         user_name: 'heemankv'


# File: .github/workflows/repo-sync.yml

# on:
#   schedule:
#   - cron:  "*/15 * * * *"
#   workflow_dispatch:

# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         persist-credentials: false
#     - name: repo-sync
#       uses: repo-sync/github-sync@v2
#       with:
#         source_repo: ""
#         source_branch: ""
#         destination_branch: ""
#         github_token: ${{ secrets.PAT }}


on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "PixySquare/PizzaCassino"
          source_branch: ""
          destination_repo: "heemankv/lil"
          destination_branch: ""
